---
name: Upload to PyPI

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools twine build

      - name: Build package
        run: python -m build --wheel .

      - name: Check Build
        run: |
          twine check --strict dist/*.whl

      - name: Publish package
        run: |
          twine upload dist/*.whl
